export const GameState = {
  GAME_OVER: 'GAME_OVER',
  GAME_PAUSED: 'GAME_PAUSED',
  GAME_PLAYING: 'GAME_PLAYING',
  VIEW_ABOUT: 'VIEW_ABOUT',
  VIEW_GAME_HUD: 'VIEW_GAME_HUD',
  VIEW_MAIN_MENU: 'VIEW_MAIN_MENU',
  VIEW_SETTINGS: 'VIEW_SETTINGS'
}
